openapi: 3.0.3
info:
  title: Knowledge Base Service API
  description: >
    独立的知识库问答服务，提供知识库搜索、流式会话、文档管理功能。
    基于 txtai 实现向量检索，内置 LLM 支持流式输出。
  version: 2.0.0
  license:
    name: MIT

servers:
  - url: http://{host}:{port}
    description: Knowledge base service endpoint
    variables:
      host:
        default: localhost
      port:
        default: "8080"

paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check
      description: Check service health, txtai and LLM availability
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /chat:
    post:
      operationId: chatStream
      summary: Chat with knowledge base (streaming)
      description: >
        Send a message and receive streaming response with RAG pipeline:
        query processing, knowledge search, context building, LLM inference.
        Response is Server-Sent Events (SSE) stream.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
      responses:
        "200":
          description: Streaming response
          content:
            text/event-stream:
              schema:
                $ref: "#/components/schemas/ChatStreamEvent"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /provider/health:
    get:
      operationId: providerHealthCheck
      summary: Provider health check (legacy)
      description: Check provider health and txtai availability
      responses:
        "200":
          description: Provider is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /provider/search:
    post:
      operationId: searchKnowledge
      summary: Search knowledge base
      description: Search knowledge base using hybrid retrieval (vector + keyword)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProviderSearchRequest"
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProviderSearchResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Provider error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /documents:
    post:
      operationId: uploadDocument
      summary: Upload and index a document
      description: Upload a document for indexing into the knowledge base
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentUploadRequest"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/FileUploadRequest"
      responses:
        "200":
          description: Document uploaded and indexed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentUploadResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      operationId: listDocuments
      summary: List all documents
      description: List all indexed documents in the knowledge base
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: List of documents
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentListResponse"

  /documents/{documentId}:
    get:
      operationId: getDocument
      summary: Get document details
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Document details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "404":
          description: Document not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      operationId: deleteDocument
      summary: Delete a document
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Document deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResponse"
        "404":
          description: Document not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: User message
        threadId:
          type: string
          description: Thread ID for conversation continuity
        runId:
          type: string
          description: Run ID for this request
        user_id:
          type: string
          description: User ID for personalization
        options:
          type: object
          properties:
            search_limit:
              type: integer
              default: 5
              description: Max knowledge chunks to retrieve
            temperature:
              type: number
              default: 0.7
              description: LLM temperature
            max_tokens:
              type: integer
              default: 2048
              description: Max response tokens
            include_sources:
              type: boolean
              default: true
              description: Include source references in response

    ChatStreamEvent:
      type: object
      description: >
        SSE event in the chat stream (AG-UI Protocol compatible).
        Event types: RUN_STARTED, TEXT_MESSAGE_START, TEXT_MESSAGE_CHUNK,
        TEXT_MESSAGE_END, RUN_FINISHED, RUN_ERROR, CUSTOM
      required:
        - type
        - threadId
        - runId
      properties:
        type:
          type: string
          description: AG-UI event type
          enum:
            - RUN_STARTED
            - TEXT_MESSAGE_START
            - TEXT_MESSAGE_CHUNK
            - TEXT_MESSAGE_END
            - RUN_FINISHED
            - RUN_ERROR
            - CUSTOM
        threadId:
          type: string
          description: Thread/conversation ID
        runId:
          type: string
          description: Run ID for this request
        messageId:
          type: string
          description: Message ID (for TEXT_MESSAGE_* events)
        role:
          type: string
          enum:
            - assistant
            - user
          description: Message role (for TEXT_MESSAGE_START)
        delta:
          type: string
          description: Text content chunk (for TEXT_MESSAGE_CHUNK)
        error:
          type: string
          description: Error message (for RUN_ERROR)
        name:
          type: string
          description: Custom event name (for CUSTOM type)
        value:
          type: object
          additionalProperties: true
          description: Custom event value (for CUSTOM type, e.g. sources, usage)

    SourceReference:
      type: object
      properties:
        chunk_id:
          type: string
        document_title:
          type: string
        content_preview:
          type: string
          description: First 100 chars of content
        score:
          type: number

    TokenUsage:
      type: object
      properties:
        prompt_tokens:
          type: integer
        completion_tokens:
          type: integer
        total_tokens:
          type: integer

    HealthResponse:
      type: object
      required:
        - status
        - version
      properties:
        status:
          type: string
          enum:
            - healthy
            - degraded
            - unhealthy
        version:
          type: string
        txtai:
          type: object
          properties:
            available:
              type: boolean
            url:
              type: string
        llm:
          type: object
          properties:
            provider:
              type: string
            model:
              type: string
            available:
              type: boolean

    ProviderSearchRequest:
      type: object
      required:
        - user_id
        - query
      properties:
        user_id:
          type: string
          description: User ID for access control and personalization
        query:
          type: string
          description: Search query text
        limit:
          type: integer
          default: 5
          minimum: 1
          maximum: 20
          description: Maximum number of chunks to return
        token_budget:
          type: integer
          description: Token budget for results
        filters:
          type: object
          additionalProperties: true
          description: Provider-specific filters
        metadata:
          type: object
          additionalProperties: true
          description: Additional context

    ProviderSearchResponse:
      type: object
      required:
        - provider_name
        - chunks
        - total_tokens
      properties:
        provider_name:
          type: string
          description: Provider identifier
        chunks:
          type: array
          items:
            $ref: "#/components/schemas/ProviderChunk"
        total_tokens:
          type: integer
          description: Total token count of all chunks
        metadata:
          type: object
          additionalProperties: true
          description: Provider-specific metadata

    ProviderChunk:
      type: object
      required:
        - chunk_id
        - content
        - score
      properties:
        chunk_id:
          type: string
          description: Unique chunk identifier
        content:
          type: string
          description: Chunk text content
        score:
          type: number
          minimum: 0
          maximum: 1
          description: Relevance score 0-1
        document_id:
          type: string
          description: Source document ID
        document_title:
          type: string
          description: Source document title
        media_type:
          type: string
          description: Type of media content
          enum:
            - text
            - image
            - video
            - audio
        media_url:
          type: string
          format: uri
          description: URL to the media file
        metadata:
          type: object
          additionalProperties: true
          description: Chunk-specific metadata

    DocumentUploadRequest:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: Document title
        content:
          type: string
          description: Document content
        category:
          type: string
          description: Document category
        description:
          type: string
          description: Document description
        metadata:
          type: object
          additionalProperties: true
          description: Custom metadata

    FileUploadRequest:
      type: object
      required:
        - title
        - file
      properties:
        title:
          type: string
          description: Document title
        file:
          type: string
          format: binary
          description: File to upload
        category:
          type: string
          description: Document category
        description:
          type: string
          description: Document description
        metadata:
          type: string
          description: JSON string of custom metadata

    DocumentUploadResponse:
      type: object
      required:
        - document_id
        - status
      properties:
        document_id:
          type: string
        status:
          type: string
          enum:
            - indexed
            - processing
            - failed
        chunks_count:
          type: integer
          description: Number of chunks created
        message:
          type: string

    Document:
      type: object
      required:
        - document_id
        - title
        - created_at
        - status
      properties:
        document_id:
          type: string
        title:
          type: string
        category:
          type: string
        description:
          type: string
        media_type:
          type: string
          description: Type of media content
          enum:
            - text
            - image
            - video
            - audio
        media_url:
          type: string
          format: uri
          description: URL to the stored media file
        status:
          type: string
          enum:
            - indexed
            - processing
            - failed
        chunks_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        metadata:
          type: object
          additionalProperties: true

    DocumentListResponse:
      type: object
      required:
        - documents
        - total
      properties:
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    DeleteResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        message:
          type: string

    ErrorResponse:
      type: object
      required:
        - error
        - code
      properties:
        error:
          type: string
        code:
          type: string
        details:
          type: object
          additionalProperties: true
